import { Product, Category } from '@/types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'For Data Scientists',
    slug: 'data-science',
    icon: '🧪',
    description: 'Workstations with high-speed GPUs and multi-core CPUs optimized for deep learning models and large datasets.',
    productCount: 48,
  },
  {
    id: '2',
    name: 'For 4K Video Editors',
    slug: 'video-editing',
    icon: '🎬',
    description: 'Ultra-accurate monitors and fast rendering processors. Smooth playback for Premiere Pro and DaVinci Resolve.',
    productCount: 35,
  },
  {
    id: '3',
    name: 'For 3D Artists',
    slug: '3d-artists',
    icon: '🎨',
    description: 'Powerful workstations built for complex geometry handling, real-time ray-tracing, and fast render times.',
    productCount: 29,
  },
  {
    id: '4',
    name: 'Gaming Setups',
    slug: 'gaming',
    icon: '🎮',
    description: 'High-refresh displays, top-tier GPUs, and peripherals for competitive and immersive gaming.',
    productCount: 62,
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'NVIDIA RTX 4090 OC Edition 24GB',
    slug: 'nvidia-rtx-4090-oc',
    brand: 'NVIDIA',
    category: 'GPUs',
    image: '/products/gpu.svg',
    rating: 4.9,
    reviewCount: 2341,
    specs: {
      'GPU': 'RTX 4090',
      'Memory': '24GB GDDR6X',
      'Clock': '2.52 GHz',
      'TDP': '450W',
    },
    tags: ['Top Pick', 'Gaming'],
    prices: [
      { marketplace: 'Amazon', price: 1599, originalPrice: 1799, url: '#', shipping: 'Free Shipping', color: '#FF9900' },
      { marketplace: 'Best Buy', price: 1649, url: '#', shipping: '$9.99 Shipping', color: '#0046BE' },
      { marketplace: 'Newegg', price: 1579, url: '#', shipping: 'Free Shipping', color: '#E66100' },
    ],
    priceHistory: [
      { date: 'Aug', price: 1899 }, { date: 'Sep', price: 1849 },
      { date: 'Oct', price: 1799 }, { date: 'Nov', price: 1699 },
      { date: 'Dec', price: 1649 }, { date: 'Jan', price: 1599 },
    ],
    trend: 'down',
    trendPercent: 8,
    aiVerdict: {
      score: 4.8,
      pros: ['Incredible gaming performance with RTX 4090', 'Stunning 4K 120Hz display option', '24GB GDDR6X memory'],
      cons: ['High power consumption', 'Premium pricing', 'Large form factor'],
    },
  },
  {
    id: '2',
    name: 'MacBook Pro 16" M3 Max',
    slug: 'macbook-pro-16-m3-max',
    brand: 'Apple',
    category: 'Laptops',
    image: '/products/laptop.svg',
    rating: 4.8,
    reviewCount: 1856,
    specs: {
      'Chip': 'M3 Max',
      'RAM': '36GB',
      'Storage': '512GB SSD',
      'Display': '16.2" XDR',
    },
    tags: ['Top Pick'],
    prices: [
      { marketplace: 'Amazon', price: 3499, url: '#', shipping: 'Free Shipping', color: '#FF9900' },
      { marketplace: 'Best Buy', price: 3499, url: '#', shipping: 'Free Shipping', color: '#0046BE' },
      { marketplace: 'Apple', price: 3499, url: '#', shipping: 'Free Shipping', color: '#333333' },
    ],
    priceHistory: [
      { date: 'Aug', price: 3699 }, { date: 'Sep', price: 3599 },
      { date: 'Oct', price: 3549 }, { date: 'Nov', price: 3499 },
      { date: 'Dec', price: 3499 }, { date: 'Jan', price: 3499 },
    ],
    trend: 'stable',
    trendPercent: 0,
    aiVerdict: {
      score: 4.7,
      pros: ['Best-in-class laptop performance', 'Outstanding battery life', 'Beautiful XDR display'],
      cons: ['High starting price', 'Limited port selection', 'Not upgradeable'],
    },
  },
  {
    id: '3',
    name: 'Dell UltraSharp 40" Curved WUHD',
    slug: 'dell-ultrasharp-40-curved',
    brand: 'Dell',
    category: 'Monitors',
    image: '/products/monitor.svg',
    rating: 4.6,
    reviewCount: 892,
    specs: {
      'Size': '40"',
      'Resolution': '5K2K (5120x2160)',
      'Panel': 'IPS Black',
      'Refresh': '120Hz',
    },
    tags: ['Hot Deal'],
    prices: [
      { marketplace: 'Amazon', price: 1299, originalPrice: 1499, url: '#', shipping: 'Free Shipping', color: '#FF9900' },
      { marketplace: 'Dell', price: 1399, url: '#', shipping: 'Free Shipping', color: '#007DB8' },
      { marketplace: 'Best Buy', price: 1349, url: '#', shipping: 'Free Shipping', color: '#0046BE' },
    ],
    priceHistory: [
      { date: 'Aug', price: 1599 }, { date: 'Sep', price: 1549 },
      { date: 'Oct', price: 1499 }, { date: 'Nov', price: 1399 },
      { date: 'Dec', price: 1349 }, { date: 'Jan', price: 1299 },
    ],
    trend: 'down',
    trendPercent: 13,
    aiVerdict: {
      score: 4.5,
      pros: ['Massive curved workspace', 'Excellent color accuracy', 'Thunderbolt 4 connectivity'],
      cons: ['Expensive', 'Needs powerful GPU', 'Large desk footprint'],
    },
  },
  {
    id: '4',
    name: 'NZXT H9 Flow Dual-Chamber',
    slug: 'nzxt-h9-flow',
    brand: 'NZXT',
    category: 'Cases',
    image: '/products/case.svg',
    rating: 4.7,
    reviewCount: 1234,
    specs: {
      'Type': 'Mid Tower',
      'Fans': '4 Included',
      'GPU Clearance': '435mm',
      'Radiator': '360mm Top/Side',
    },
    tags: [],
    prices: [
      { marketplace: 'Amazon', price: 159, url: '#', shipping: 'Free Shipping', color: '#FF9900' },
      { marketplace: 'Newegg', price: 154, url: '#', shipping: 'Free Shipping', color: '#E66100' },
    ],
    priceHistory: [
      { date: 'Aug', price: 179 }, { date: 'Sep', price: 174 },
      { date: 'Oct', price: 169 }, { date: 'Nov', price: 164 },
      { date: 'Dec', price: 159 }, { date: 'Jan', price: 159 },
    ],
    trend: 'stable',
    trendPercent: 0,
    aiVerdict: {
      score: 4.6,
      pros: ['Excellent airflow design', 'Beautiful dual-chamber aesthetics', 'Easy cable management'],
      cons: ['Large size', 'Premium pricing for a case', 'Heavy when fully built'],
    },
  },
  {
    id: '5',
    name: 'ASUS ROG Zephyrus G14',
    slug: 'asus-rog-zephyrus-g14',
    brand: 'ASUS',
    category: 'Laptops',
    image: '/products/laptop.svg',
    rating: 4.5,
    reviewCount: 1567,
    specs: {
      'CPU': 'Ryzen 9',
      'RAM': '16GB',
      'Storage': '1TB SSD',
      'Display': '14" 165Hz',
    },
    tags: ['Gaming'],
    prices: [
      { marketplace: 'Amazon', price: 1299, url: '#', shipping: 'Free Shipping', color: '#FF9900' },
      { marketplace: 'Best Buy', price: 1249, url: '#', shipping: 'Free Shipping', color: '#0046BE' },
      { marketplace: 'Newegg', price: 1279, url: '#', shipping: 'Free Shipping', color: '#E66100' },
    ],
    priceHistory: [
      { date: 'Aug', price: 1499 }, { date: 'Sep', price: 1449 },
      { date: 'Oct', price: 1399 }, { date: 'Nov', price: 1349 },
      { date: 'Dec', price: 1299 }, { date: 'Jan', price: 1249 },
    ],
    trend: 'down',
    trendPercent: 5,
    aiVerdict: {
      score: 4.4,
      pros: ['Compact gaming powerhouse', 'Great display quality', 'Portable form factor'],
      cons: ['Can get warm under load', 'Average webcam', 'Keyboard layout takes time to adjust'],
    },
  },
  {
    id: '6',
    name: 'Lenovo ThinkPad X1 Carbon',
    slug: 'lenovo-thinkpad-x1-carbon',
    brand: 'Lenovo',
    category: 'Laptops',
    image: '/products/laptop.svg',
    rating: 4.6,
    reviewCount: 2089,
    specs: {
      'CPU': 'Core i7',
      'RAM': '32GB',
      'Storage': '512GB SSD',
      'Display': '14" IPS',
    },
    tags: ['Business'],
    prices: [
      { marketplace: 'Amazon', price: 1649, url: '#', shipping: 'Free Shipping', color: '#FF9900' },
      { marketplace: 'Lenovo', price: 1599, url: '#', shipping: 'Free Shipping', color: '#E2231A' },
    ],
    priceHistory: [
      { date: 'Aug', price: 1799 }, { date: 'Sep', price: 1749 },
      { date: 'Oct', price: 1699 }, { date: 'Nov', price: 1649 },
      { date: 'Dec', price: 1649 }, { date: 'Jan', price: 1649 },
    ],
    trend: 'down',
    trendPercent: 3,
    aiVerdict: {
      score: 4.5,
      pros: ['Legendary keyboard', 'Ultra-light and durable', 'All-day battery life'],
      cons: ['Pricey for specs offered', 'No discrete GPU option', 'Soldered RAM'],
    },
  },
];

export const mockDellProduct: Product = {
  id: 'dell-1',
  name: 'Alienware x17 R2',
  slug: 'alienware-x17-r2',
  brand: 'Dell',
  category: 'Laptops',
  image: '/products/laptop.svg',
  rating: 4.8,
  reviewCount: 1243,
  specs: {
    'CPU': 'Intel Core i9-12900HK',
    'GPU': 'NVIDIA GeForce RTX 3080 Ti',
    'VRAM': '16GB GDDR6',
    'TDP': '175W Max',
    'RAM': '32GB DDR5 4800MHz',
    'Slots': '2x SO-DIMM (Up to 64GB)',
    'SSD': '1TB NVMe PCIe Gen 4',
    'Size': '17.3 inch',
    'Resolution': 'QHD (2560 × 2560 OQHD)',
    'Features': '100% Adobe/RGB, 165 nits, G-Sync',
    'WiFi': 'Wi-Fi 6E (802.11ax)',
    'Bluetooth': '5.2',
    'Ports': '1x TB4, 2x USB-A 3.2, 1x HDMI 2.1',
    'Dimensions': '399 × 290 × 21 mm',
    'Weight': '3.02 kg (6.65 lbs)',
    'Battery': '87 Wh, 330W Adapter',
    'OS': 'Windows 11 Pro',
    'Webcam': '720p HD with IR',
    'Keyboard': 'CherryMX Mechanical Per-Key RGB',
  },
  tags: ['Top Choice', 'Gaming'],
  prices: [
    { marketplace: 'Amazon', price: 2899, url: '#', shipping: 'Free Shipping', color: '#FF9900' },
    { marketplace: 'Best Buy', price: 2949, originalPrice: 3199, url: '#', shipping: 'Price Match', color: '#0046BE' },
    { marketplace: 'Newegg', price: 2999, url: '#', shipping: '$9.99 Shipping', color: '#E66100' },
  ],
  priceHistory: [
    { date: 'Aug', price: 3299 }, { date: 'Sep', price: 3199 },
    { date: 'Oct', price: 3099 }, { date: 'Nov', price: 2999 },
    { date: 'Dec', price: 2949 }, { date: 'Jan', price: 2899 },
  ],
  trend: 'down',
  trendPercent: 12,
  aiVerdict: {
    score: 4.8,
    pros: [
      'Incredible gaming performance with RTX 3080 Ti',
      'Stunning 4K 120Hz display option',
      'Battery life is mediocre for productivity',
    ],
    cons: [
      'Very heavy at 3kg',
      'Expensive starting price',
      'Fan noise under heavy load',
    ],
  },
};
